// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  "apiKey": "AIzaSyConaLMGbmuUyXc0uPK6E3La_PPeKjeVno",
  "authDomain": "studio-4703824518-7192d.firebaseapp.com",
  "projectId": "studio-4703824518-7192d",
  "storageBucket": "studio-4703824518-7192d.appspot.com",
  "messagingSenderId": "624173814853",
  "appId": "1:624173814853:web:5ef00936897789bd6fff2c",
  "measurementId": "G-5G3Q5Z3B1P"
};
